# Generated by Django 5.2.12 on 2026-03-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('company_name', models.TextField()),
                ('country', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('industry', models.TextField()),
                ('application', models.TextField()),
                ('purity', models.TextField()),
                ('volume', models.TextField()),
                ('packaging', models.TextField()),
                ('delivery_terms', models.TextField()),
                ('destination_port', models.TextField()),
                ('additional_specs', models.TextField()),
            ],
        ),
    ]
